### ISSUE TITLE
Hosting on a single node?

### ISSUE THREAD

**Issue by weaversam8** [symkat/MarkdownSite#8]
This is an exciting project- I've been looking for something like this for a long time.

One blocker for me is the challenge of requiring a minimum of four servers to spin up a MarkdownSite setup (as documented in [`devops/`](https://github.com/symkat/MarkdownSite/tree/master/devops).)

Is it possible to host MarkdownSite on a single server instead of four? If not, is this planned for the future?

**Comment by symkat** [comment]
Hi Sam!

Thank you for the feedback, and I hope MarkdownSite ends up having been the right thing to find!

The short answer is: Most probably you could get away with two instances and be happy with little effort.  There is a problem to solve if you really want one instance.

The four server setup needs and insight server, a build server, a panel server, and a web server to host the websites.  You could do away with the insight server completely.  Then you could make the panel server also run the build server programs (the minion worker service file), and have the ansible deployment stuff on it.  This combines the panel and the build server into one and there wouldn’t be any conflicts.

Where you run into conflicts is that web server for end users.  It runs lighttpd on port 80/443 to serve end user websites.  The panel server uses nginx.  It’s very important that the end user server runs lighttpd so that CGI mode (lacking in nginx) can work for MarkdownSite::CGI.  If these are two instances, then you have one server running the panel/postgres/builder/nginx and one server running lighttpd.  The panel deploys things to the server running lighttpd.

To combine those further into one, if push comes to shove, you’d want to change the nginx stuff on the panel so that you’re using lighted to run the panel software, and then you’re down to one server.

It’s currently not a path I’m looking much at to have it run on one instance only, so I’m unlikely to approach solving that myself in the near term.

The dual instance setup with one server running all the Panel/Builder and one server being the web server that things are deployed to is one I think could be really neat.

—

The two things that I’m focused on right now are making a real user panel, and unifying the installation and configuration management into one system to make a whole bunch of the documentation you’re reading no longer valid soon (well, the installation, all the architecture stuff is the same).

The real user panel is the Panel and Panel-DB folders, they’ll replace the Manager/Manager-DB packages that have the “Enter your git repo” as the only UI.  This new one allows user login, has a guided walk-through for connecting a repo, supports multiple build systems (so that, for example, a Jekyll blog can be committed in an unbuilt state, and the Jekyll builder will run docker containers with rootless podman to create the build artifacts, and then push that to the web server).  This is deployed to https://mds-beta.com now if you want to see how the control panel is going to be.

For the second thing, I’ve added devops/ansible.  The installation steps should soon be down to choose your domains, get ssl certs, add an inventory file and some host variables and run ansible-playbook and wait.  With this, I could see making that two-node setup and having an example inventory file would work — I suppose it could just be running the panel and builder roles on one machine, the web server role on another.

**Comment by weaversam8** [comment]
This is an awesome and very detailed answer, thanks Kate!

If I try the dual-instance setup, I'll let you know how it goes! One small question- you said that in order to move to a single-node setup, you'd need to swap nginx out for lighttpd so you didn't sacrifice the CGI support. Why not run both and use nginx to proxy traffic to lighttpd? Is there something about lighttpd's CGI setup that would break in that scenario?

(P.S.: the user panel stuff looks great! excited to see it develop further!)

**Comment by symkat** [comment]
You’re most welcome!

> Why not run both and use nginx to proxy traffic to lighttpd?

I think you’re onto something there.  If you run lighty on an alternative/localhost ip, and then proxied unknown connections (probably just overwrite /etc/nginx/sites-enabled/default with the stream proxy), directly to lighty, you’d probably get it all on one node.

I’ll close this issue out for now — if you do something like that in a fork or a write up, let me know and I’ll include links in the readme!
